/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EscrowPayment {
  'status' : PaymentStatus,
  'taskerUpiId' : string,
  'taskId' : string,
  'razorpayOrderId' : string,
  'paymentId' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'PAID' : null } |
  { 'COMPLETED' : null } |
  { 'FAILED' : null };
export interface PublicPickupDropTask {
  'id' : string,
  'razorpayPaymentId' : string,
  'status' : string,
  'pickupContact' : string,
  'taskerFee' : bigint,
  'pickupOwnerName' : string,
  'createdAt' : bigint,
  'dropOwnerName' : string,
  'dropContact' : string,
  'dropLocation' : string,
  'razorpayOrderId' : string,
  'acceptor' : [] | [Principal],
  'boostFee' : bigint,
  'productWorth' : bigint,
  'pickupLocation' : string,
  'poster' : Principal,
}
export interface PublicTask {
  'id' : string,
  'status' : TaskStatus,
  'completedAt' : [] | [bigint],
  'title' : string,
  'taskerFee' : bigint,
  'productAmount' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'boost' : bigint,
  'acceptor' : [] | [Principal],
  'acceptedAt' : [] | [bigint],
  'amount' : bigint,
  'location' : string,
  'poster' : Principal,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Task {
  'id' : string,
  'otp' : string,
  'status' : TaskStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'acceptor' : [] | [Principal],
  'amount' : bigint,
  'location' : string,
  'poster' : Principal,
}
export interface TaskParticipantProfiles {
  'taskerProfile' : [] | [UserProfile],
  'posterProfile' : [] | [UserProfile],
}
export interface TaskStageResponse { 'stage' : string, 'timestamp' : bigint }
export type TaskStatus = { 'open' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'studentId' : [] | [string],
  'name' : string,
  'aadharNumber' : [] | [string],
  'upiId' : string,
  'phone' : string,
  'location' : string,
}
export interface UserProfileEntry {
  'principal' : string,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptPickupDropTask' : ActorMethod<[string, string, string], Result>,
  'acceptTask' : ActorMethod<[string], [] | [PublicTask]>,
  'advanceTaskStage' : ActorMethod<[string, string], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTask' : ActorMethod<[string], Result>,
  'completePickupDropDelivery' : ActorMethod<[string, string], Result>,
  'completePickupDropPickup' : ActorMethod<[string, string], Result>,
  'completeTask' : ActorMethod<[string, string], [] | [PublicTask]>,
  'countTasks' : ActorMethod<[], bigint>,
  'createPickupDropTask' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      string,
    ],
    string
  >,
  'createRazorpayOrder' : ActorMethod<[bigint, string, string, string], Result>,
  'createTask' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint],
    [] | [string]
  >,
  'failPickupDropTask' : ActorMethod<[string], Result>,
  'getAllPickupDropTasksAdmin' : ActorMethod<[], Array<PublicPickupDropTask>>,
  'getAllTasks' : ActorMethod<[], Array<PublicTask>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAcceptedTasks' : ActorMethod<[], Array<PublicTask>>,
  'getMyPickupDropAcceptedTasks' : ActorMethod<[], Array<PublicPickupDropTask>>,
  'getMyPickupDropPostedTasks' : ActorMethod<[], Array<PublicPickupDropTask>>,
  'getMyPostedTasks' : ActorMethod<[], Array<PublicTask>>,
  'getPaymentByTask' : ActorMethod<[string], [] | [EscrowPayment]>,
  'getPayments' : ActorMethod<[], Array<EscrowPayment>>,
  'getPickupDropTask' : ActorMethod<[string], [] | [PublicPickupDropTask]>,
  'getPickupDropTasks' : ActorMethod<[], Array<PublicPickupDropTask>>,
  'getTask' : ActorMethod<[string], [] | [PublicTask]>,
  'getTaskParticipantProfiles' : ActorMethod<
    [string],
    [] | [TaskParticipantProfiles]
  >,
  'getTaskStage' : ActorMethod<[string], [] | [TaskStageResponse]>,
  'getTaskWithOtp' : ActorMethod<[string], [] | [Task]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPayoutComplete' : ActorMethod<[string], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyPayment' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];