/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskStatus = IDL.Variant({
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PublicTask = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'acceptor' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Nat,
  'location' : IDL.Text,
  'poster' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserProfile = IDL.Record({
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'aadharNumber' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'PAID' : IDL.Null,
  'COMPLETED' : IDL.Null,
  'FAILED' : IDL.Null,
});
export const EscrowPayment = IDL.Record({
  'status' : PaymentStatus,
  'taskerUpiId' : IDL.Text,
  'taskId' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'paymentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'otp' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'acceptor' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Nat,
  'location' : IDL.Text,
  'poster' : IDL.Principal,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTask' : IDL.Func([IDL.Text], [IDL.Opt(PublicTask)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(PublicTask)], []),
  'countTasks' : IDL.Func([], [IDL.Nat], ['query']),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAcceptedTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
  'getMyPostedTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
  'getPaymentByTask' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EscrowPayment)],
      ['query'],
    ),
  'getPayments' : IDL.Func([], [IDL.Vec(EscrowPayment)], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(PublicTask)], ['query']),
  'getTaskWithOtp' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPayoutComplete' : IDL.Func([IDL.Text], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskStatus = IDL.Variant({
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PublicTask = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'acceptor' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Nat,
    'location' : IDL.Text,
    'poster' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'aadharNumber' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'PAID' : IDL.Null,
    'COMPLETED' : IDL.Null,
    'FAILED' : IDL.Null,
  });
  const EscrowPayment = IDL.Record({
    'status' : PaymentStatus,
    'taskerUpiId' : IDL.Text,
    'taskId' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'paymentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'otp' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'acceptor' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Nat,
    'location' : IDL.Text,
    'poster' : IDL.Principal,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTask' : IDL.Func([IDL.Text], [IDL.Opt(PublicTask)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(PublicTask)], []),
    'countTasks' : IDL.Func([], [IDL.Nat], ['query']),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAcceptedTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
    'getMyPostedTasks' : IDL.Func([], [IDL.Vec(PublicTask)], ['query']),
    'getPaymentByTask' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EscrowPayment)],
        ['query'],
      ),
    'getPayments' : IDL.Func([], [IDL.Vec(EscrowPayment)], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(PublicTask)], ['query']),
    'getTaskWithOtp' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPayoutComplete' : IDL.Func([IDL.Text], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };